activities = [
    ["Soccer", "both", ["Summer", "Spring", "Fall"], 6, 22, "Weekend"],
    ["Basketball", "both", ["Summer", "Spring", "Fall"], 4, 12, "Weekend"],
    ["Tennis", "both", ["Summer", "Fall"], 2, 4, "Weekend"],
    ["Swimming", "both", ["Summer", "Spring", "Fall", "Winter"], 1, 10, "Weekday"],
    ["Hiking", "outdoor", ["Summer", "Fall"], 2, 6, "Weekend"],
    ["Nature walks", "outdoor", ["Summer", "Fall"], 2, 6, "Weekday"],
    ["Birdwatching", "outdoor", ["Summer"], 1, 4, "Weekday"],
    ["Painting", "outdoor", ["Summer", "Spring", "Fall", "Winter"], 1, 4, "Weekday"],
    ["Drawing", "outdoor", ["Summer", "Spring", "Fall", "Winter"], 1, 4, "Weekday"],
    ["Pottery", "outdoor", ["Summer", "Spring", "Fall", "Winter"], 1, 4, "Weekday"],
    ["Dancing", "outdoor", ["Summer", "Spring", "Fall", "Winter"], 2, 8, "Weekday"],
    ["Singing", "outdoor", ["Summer", "Spring", "Fall", "Winter"], 3, 10, "Weekday"],
    ["Library", "outdoor", ["Summer", "Spring", "Fall", "Winter"], 1, 5, "Weekday"],
    ["Creative writing", "outdoor", ["Summer", "Spring", "Fall", "Winter"], 1, 4, "Weekday"],
    ["Drama club", "outdoor", ["Summer", "Spring", "Fall", "Winter"], 4, 10, "Weekday"],
    ["Puppet shows", "outdoor", ["Summer", "Spring", "Fall", "Winter"], 1, 5, "Weekday"],
    ["Movies", "outdoor", ["Summer", "Spring", "Fall", "Winter"], 1, 5, "Weekend"],
    ["Chess", "both", ["Summer", "Spring", "Fall", "Winter"], 2, 2, "Weekday"],
    ["Puzzle solving", "indoor", ["Summer", "Spring", "Fall", "Winter"], 1, 4, "Weekday"],
    ["Strategy games", "both", ["Summer", "Spring", "Fall", "Winter"], 2, 4, "Weekday"],
    ["Baking", "indoor", ["Summer", "Spring", "Fall", "Winter"], 1, 4, "Weekday"],
    ["Cooking classes", "indoor", ["Summer", "Spring", "Fall", "Winter"], 1, 4, "Weekday"],
    ["Video games", "indoor", ["Summer", "Spring", "Fall", "Winter"], 1, 4, "Weekend"],
    ["Martial Arts", "indoor", ["Summer", "Spring", "Fall", "Winter"], 1, 6, "Weekday"],
    ["Yoga", "both", ["Summer", "Fall"], 1, 5, "Weekday"],
    ["Meditation", "both", ["Summer", "Spring", "Fall", "Winter"], 1, 5, "Weekday"],
    ["Volunteer work", "both", ["Summer"], 1, 10, "Weekday"],
    ["Community cleanup", "outdoor", ["Summer"], 2, 10, "Weekend"],
    ["Dog walking", "outdoor", ["Summer", "Fall"], 1, 4, "Weekday"],
    ["Horse riding", "outdoor", ["Summer"], 1, 4, "Weekend"],
    ["Language clubs", "indoor", ["Summer", "Spring", "Fall", "Winter"], 1, 8, "Weekday"],
    ["Cultural dance", "both", ["Summer", "Spring", "Fall", "Winter"], 3, 10, "Weekend"],
    ["Rock climbing", "both", ["Summer", "Spring", "Fall", "Winter"], 2, 5, "Weekend"],
    ["Skating", "indoor", ["Summer", "Spring", "Fall", "Winter"], 1, 8, "Weekday"],
    ["BMX biking", "outdoor", ["Summer", "Fall"], 1, 6, "Weekend"],
    ["Lego building", "indoor", ["Summer", "Spring", "Fall", "Winter"], 1, 6, "Weekday"],
    ["Aircraft models", "indoor", ["Summer", "Spring", "Fall", "Winter"], 1, 3, "Weekday"],
    ["Ship models", "indoor", ["Summer", "Spring", "Fall", "Winter"], 1, 3, "Weekday"],
    ["Woodworking", "indoor", ["Summer", "Spring", "Fall", "Winter"], 1, 4, "Weekday"],
    ["Sewing and Fashion Design", "indoor", ["Summer", "Spring", "Fall", "Winter"], 1, 4, "Weekday"],
    ["Museum visits", "indoor", ["Summer", "Spring", "Fall", "Winter"], 1, 4, "Weekend"],
    ["Historic site visits", "both", ["Summer", "Spring", "Fall"], 1, 4, "Weekend"],
    ["Fishing", "outdoor", ["Summer", "Spring"], 1, 6, "Weekend"],
    ["Escape rooms", "indoor", ["Summer", "Spring", "Fall", "Winter"], 3, 8, "Weekday"],
    ["Hopscotch", "outdoor", ["Summer", "Fall"], 2, 4, "Weekday"],
    ["Hide and seek", "both", ["Summer", "Fall"], 4, 10, "Weekday"],
    ["Water park", "outdoor", ["Summer"], 2, 8, "Weekend"],
    ["Camping", "outdoor", ["Summer", "Fall"], 4, 8, "Weekend"],
    ["Aquarium", "indoor", ["Summer", "Spring", "Fall", "Winter"], 2, 8, "Weekday"],
    ["Zoo", "outdoor", ["Summer", "Spring", "Fall"], 1, 8, "Weekday"],
    ["Skiing", "outdoor", ["Winter"], 1, 5, "Weekend"]
]
