activities = [
    ["Soccer", "Both", ["Summer", "Spring", "Fall"], 6, 22, "Weekend"],
    ["Basketball", "Both", ["Summer", "Spring", "Fall"], 4, 12, "Weekend"],
    ["Tennis", "Both", ["Summer", "Fall"], 2, 4, "Weekend"],
    ["Swimming", "Both", ["Summer", "Spring", "Fall", "Winter"], 1, 10, "Weekday"],
    ["Hiking", "Outdoor", ["Summer", "Fall"], 2, 6, "Weekend"],
    ["Nature walks", "Outdoor", ["Summer", "Fall"], 2, 6, "Weekday"],
    ["Birdwatching", "Outdoor", ["Summer"], 1, 4, "Weekday"],
    ["Painting", "Outdoor", ["Summer", "Spring", "Fall", "Winter"], 1, 4, "Weekday"],
    ["Drawing", "Outdoor", ["Summer", "Spring", "Fall", "Winter"], 1, 4, "Weekday"],
    ["Pottery", "Outdoor", ["Summer", "Spring", "Fall", "Winter"], 1, 4, "Weekday"],
    ["Dancing", "Outdoor", ["Summer", "Spring", "Fall", "Winter"], 2, 8, "Weekday"],
    ["Singing", "Outdoor", ["Summer", "Spring", "Fall", "Winter"], 3, 10, "Weekday"],
    ["Library", "Outdoor", ["Summer", "Spring", "Fall", "Winter"], 1, 5, "Weekday"],
    ["Creative writing", "Outdoor", ["Summer", "Spring", "Fall", "Winter"], 1, 4, "Weekday"],
    ["Drama club", "Outdoor", ["Summer", "Spring", "Fall", "Winter"], 4, 10, "Weekday"],
    ["Puppet shows", "Outdoor", ["Summer", "Spring", "Fall", "Winter"], 1, 5, "Weekday"],
    ["Movies", "Outdoor", ["Summer", "Spring", "Fall", "Winter"], 1, 5, "Weekend"],
    ["Chess", "Both", ["Summer", "Spring", "Fall", "Winter"], 2, 2, "Weekday"],
    ["Puzzle solving", "Indoor", ["Summer", "Spring", "Fall", "Winter"], 1, 4, "Weekday"],
    ["Strategy games", "Both", ["Summer", "Spring", "Fall", "Winter"], 2, 4, "Weekday"],
    ["Baking", "Indoor", ["Summer", "Spring", "Fall", "Winter"], 1, 4, "Weekday"],
    ["Cooking classes", "Indoor", ["Summer", "Spring", "Fall", "Winter"], 1, 4, "Weekday"],
    ["Video games", "Indoor", ["Summer", "Spring", "Fall", "Winter"], 1, 4, "Weekend"],
    ["Martial Arts", "Indoor", ["Summer", "Spring", "Fall", "Winter"], 1, 6, "Weekday"],
    ["Yoga", "Both", ["Summer", "Fall"], 1, 5, "Weekday"],
    ["Meditation", "Both", ["Summer", "Spring", "Fall", "Winter"], 1, 5, "Weekday"],
    ["Volunteer work", "Both", ["Summer"], 1, 10, "Weekday"],
    ["Community cleanup", "Outdoor", ["Summer"], 2, 10, "Weekend"],
    ["Dog walking", "Outdoor", ["Summer", "Fall"], 1, 4, "Weekday"],
    ["Horse riding", "Outdoor", ["Summer"], 1, 4, "Weekend"],
    ["Language clubs", "Indoor", ["Summer", "Spring", "Fall", "Winter"], 1, 8, "Weekday"],
    ["Cultural dance", "Both", ["Summer", "Spring", "Fall", "Winter"], 3, 10, "Weekend"],
    ["Rock climbing", "Both", ["Summer", "Spring", "Fall", "Winter"], 2, 5, "Weekend"],
    ["Skating", "Indoor", ["Summer", "Spring", "Fall", "Winter"], 1, 8, "Weekday"],
    ["BMX biking", "Outdoor", ["Summer", "Fall"], 1, 6, "Weekend"],
    ["Lego building", "Indoor", ["Summer", "Spring", "Fall", "Winter"], 1, 6, "Weekday"],
    ["Aircraft models", "Indoor", ["Summer", "Spring", "Fall", "Winter"], 1, 3, "Weekday"],
    ["Ship models", "Indoor", ["Summer", "Spring", "Fall", "Winter"], 1, 3, "Weekday"],
    ["Woodworking", "Indoor", ["Summer", "Spring", "Fall", "Winter"], 1, 4, "Weekday"],
    ["Sewing and Fashion Design", "Indoor", ["Summer", "Spring", "Fall", "Winter"], 1, 4, "Weekday"],
    ["Museum visits", "Indoor", ["Summer", "Spring", "Fall", "Winter"], 1, 4, "Weekend"],
    ["Historic site visits", "Both", ["Summer", "Spring", "Fall"], 1, 4, "Weekend"],
    ["Fishing", "Outdoor", ["Summer", "Spring"], 1, 6, "Weekend"],
    ["Escape rooms", "Indoor", ["Summer", "Spring", "Fall", "Winter"], 3, 8, "Weekday"],
    ["Hopscotch", "Outdoor", ["Summer", "Fall"], 2, 4, "Weekday"],
    ["Hide and seek", "Both", ["Summer", "Fall"], 4, 10, "Weekday"],
    ["Water park", "Outdoor", ["Summer"], 2, 8, "Weekend"],
    ["Camping", "Outdoor", ["Summer", "Fall"], 4, 8, "Weekend"],
    ["Aquarium", "Indoor", ["Summer", "Spring", "Fall", "Winter"], 2, 8, "Weekday"],
    ["Zoo", "Outdoor", ["Summer", "Spring", "Fall"], 1, 8, "Weekday"],
    ["Skiing", "Outdoor", ["Winter"], 1, 5, "Weekend"]
]
